twig:
    paths:
        'public/build/img': img
        'assets/css': styles

    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@Image/form/bootstrap_4.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        
    
    globals:
       logo_site: '/build/img/rdv.png'
       site_name: 'Rendez vous avec soi'
       site_street:  3, Rue Robespierre
       site_cp: 26500
       site_city: Bourg lès Valence
       contact_email: francoise.forite@cegetel.net
       telephone_fixe:   04 75 42 91 26
       telephone_mobile: 07 81 68 40 26
