#index:
#    path: /
#    controller: App\Controller\DefaultController::index
image:
  resource: '@ImageBundle/Resources/config/routing.yml'

elfinder:
  resource: "@FMElfinderBundle/Resources/config/routing.yaml"

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"

